#make file rabelling
rabelling: labeling.cpp label_server3.cpp
	g++ -o labeling_server3.out -lopencv_core -lopencv_imgproc -lopencv_highgui  -lopencv_contrib -I/usr/local/include/opencv -L/usr/local/lib define.h label_server3.cpp labeling.cpp 
